### ISSUE TITLE
Add 'decimal' field to security static data

### ISSUE THREAD

**Issue by jeerrry** [yizhoucao/lilith#3]
Currently front-end uses dedicated function to handle price decimal places by currency (FX by precision). It's better to customize decimal places for each security for optimal display result.
 
Areas affected:
* Firebase schema & data
* portfolioTableAdaptor @ client.js
* formatTableInput @ client.js

**Comment by yizhoucao** [comment]
Included decimal setting in security table. Both fx and equity prices are adjusted based on this setting
